//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace M_UBI_Ddjg.ServiceXLQ {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceXLQ.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBoundary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getBoundary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBoundary", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getBoundaryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBoundaryRow", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getBoundaryRow(string massNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBoundaryRow", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getBoundaryRowAsync(string massNum);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : M_UBI_Ddjg.ServiceXLQ.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<M_UBI_Ddjg.ServiceXLQ.Service1Soap>, M_UBI_Ddjg.ServiceXLQ.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getBoundary() {
            return base.Channel.getBoundary();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getBoundaryAsync() {
            return base.Channel.getBoundaryAsync();
        }
        
        public System.Data.DataSet getBoundaryRow(string massNum) {
            return base.Channel.getBoundaryRow(massNum);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getBoundaryRowAsync(string massNum) {
            return base.Channel.getBoundaryRowAsync(massNum);
        }
    }
}
